type User {
  auth0Id: String! @unique
  email: String! @unique
  nickname: String
  name: String
  setupCompleted: Boolean!
  pages: [Page!] @relation
  createdAt: String!
  updatedAt: String!
}

type Folder {
  name: String!
  owner: User!
  pages: [Page!] @relation
  createdAt: String!
  updatedAt: String!
}

type Page {
  title: String!
  published: Boolean!
  owner: User!
  folder: Folder
  contentTemporary: String
  contentBlocks: [Block]
  createdAt: String!
  updatedAt: String!
}

type Block @embedded {
  type: String!
  content: String
}

type Report {
  type: String!
  url: String
  name: String
  email: String
  description: String
  createdAt: String!
  updatedAt: String!
}

type Query {
  allUsers: [User!]
  allPages: [Page!]
}
