type People {
  auth0Id: String! @unique
  email: String! @unique
  avatar: String
  nickname: String
  name: String
  visible: Boolean!
  setupCompleted: Boolean!
  pages: [Pages!] @relation
  createdAt: String!
  updatedAt: String!
}

type Relationships {
  followee: People! @relation
  follower: People! @relation
  followedAt: String!
}

type Folders {
  name: String!
  owner: People!
  pages: [Pages!] @relation
  createdAt: String!
  updatedAt: String!
}

type Pages {
  title: String!
  published: Boolean!
  owner: People!
  folder: Folders
  contentTiptap: String
  createdAt: String!
  updatedAt: String!
}

type Reports {
  type: String!
  url: String
  name: String
  email: String
  description: String
  createdAt: String!
  updatedAt: String!
}
