type Folder {
  name: String!
  owner: User!
  pages: [Page!] @relation
  createdAt: String!
  updatedAt: String!
}

type Page {
  title: String!
  published: Boolean!
  owner: User!
  folder: Folder
  contentTemporary: String
  contentBlocks: [Block]
  createdAt: String!
  updatedAt: String!
}

type Block {
  page: Page!
  type: String!
  content: String
}

type User {
  auth0Id: String! @unique
  email: String! @unique
  nickname: String
  name: String
  setupCompleted: Boolean!
  pages: [Page!] @relation
}

type Query {
  allPages: [Page!]
  allUsers: [User!]
}
