import { useUser } from "@auth0/nextjs-auth0";
import Head from "next/head";
import DashboardLayout from "../components/layout/DashboardLayout";
import Button, { ButtonIcon } from "../components/Button";
import ArrowRightCircleIcon from "../components/svg/ArrowRightCircle";
import styled from "@emotion/styled";

Home.getLayout = (page) => <DashboardLayout>{page}</DashboardLayout>;

export default function Home() {
  const { user, error, isLoading } = useUser();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWrapper>
        {isLoading && <div>Loading...</div>}
        {error && <div>{error.message}</div>}
        {user ? (
          <>
            <h1>Welcome, {user.name}!</h1>

            <br />

            <a href="/dashboard">
              <Button>
                Dashboard
                <ButtonIcon>
                  <ArrowRightCircleIcon />
                </ButtonIcon>
              </Button>
            </a>

            <br />

            <a href="/onboarding">
              <Button>
                Onboard
                <ButtonIcon>
                  <ArrowRightCircleIcon />
                </ButtonIcon>
              </Button>
            </a>

            <br />

            <a href="/api/auth/logout">
              <Button>
                Log Out
                <ButtonIcon>
                  <ArrowRightCircleIcon />
                </ButtonIcon>
              </Button>
            </a>

            <br />
            <br />
            <br />

            <h4>Rendered user info on the client</h4>
            <pre data-testid="profile">{JSON.stringify(user, null, 2)}</pre>
          </>
        ) : (
          <a href="/api/auth/login">
            <Button>
              Log In
              <ButtonIcon>
                <ArrowRightCircleIcon />
              </ButtonIcon>
            </Button>
          </a>
        )}
      </PageWrapper>
    </div>
  );
}

export const PageWrapper = styled.main`
  margin: 0 5rem;

  a {
    color: inherit;
  }
`;
