import { useUser } from "@auth0/nextjs-auth0";
import { useFaunaUser } from "../hooks/useFaunaUser";
import Head from "next/head";
import { withDashboardLayout } from "../components/layout/DashboardLayout";
// import DashboardLayout from "../components/layout/DashboardLayout";
import Button, { ButtonIcon } from "../components/Button";
import ArrowRightCircleIcon from "../components/svg/ArrowRightCircle";
import styled from "@emotion/styled";

export default withDashboardLayout(function Home() {
  const { user, error, isLoading } = useUser();
  const { faunaUserStatus, faunaUserData } = useFaunaUser();

  return (
    <>
      <Head>
        <title>pblsh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWrapper>
        {(isLoading || faunaUserStatus !== "fetched") && <div>Loading...</div>}
        {error && <div>{error.message}</div>}
        {user && faunaUserData ? (
          <>
            <h1>Welcome, {faunaUserData.name}!</h1>

            <br />

            {faunaUserData.setupCompleted ? (
              <Button href="/dashboard">
                Dashboard
                <ButtonIcon>
                  <ArrowRightCircleIcon />
                </ButtonIcon>
              </Button>
            ) : (
              <Button href="/onboarding">
                Onboard
                <ButtonIcon>
                  <ArrowRightCircleIcon />
                </ButtonIcon>
              </Button>
            )}

            <br />

            <Button href="/api/auth/logout">
              Log Out
              <ButtonIcon>
                <ArrowRightCircleIcon />
              </ButtonIcon>
            </Button>
          </>
        ) : (
          <Button href="/api/auth/login">
            Log In
            <ButtonIcon>
              <ArrowRightCircleIcon />
            </ButtonIcon>
          </Button>
        )}
      </PageWrapper>
    </>
  );
});

export const PageWrapper = styled.main`
  margin: 0 5rem;

  a {
    color: inherit;
  }
`;
