import { useUser, withPageAuthRequired } from "@auth0/nextjs-auth0";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import DashboardLayout from "../components/layout/DashboardLayout";
import LogoColored from "../components/svg/LogoColored";
import Form, { InputGroup, InputLabel, Input } from "../components/Form";
import Button, { ButtonIcon } from "../components/Button";
import PlusCircleIcon from "../components/svg/PlusCircle";
import { css } from "@emotion/react";
import styled from "@emotion/styled";
import {
  linkStyles,
  padWithBackgroundStyles,
  padStyles,
} from "../shared/styles";

withPageAuthRequired.getLayout = (page) => (
  <DashboardLayout>{page}</DashboardLayout>
);

export default withPageAuthRequired(function Onboarding() {
  const { user } = useUser();
  const accountSetupComplete = false;

  return (
    <div>
      <Head>
        <title>Onboarding | pblsh</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <PageWrapper>
        {!accountSetupComplete ? (
          <>
            <LogoBox>
              <LogoColored />
            </LogoBox>

            <AccountSetup>
              <h1>Greetings!</h1>
              <p>Welcome to pblsh, we're so happy to have you!</p>
            </AccountSetup>

            <Block>
              <h2>Finalize Your Account</h2>
              <p>
                Before we dive in, we just need a few more pieces of
                information.
              </p>

              <FormWrapper>
                <Form>
                  <InputGroup>
                    <InputLabel htmlFor="name" l>
                      Name
                    </InputLabel>
                    <Input
                      type="text"
                      id="name"
                      name="name"
                      placeholder="Jim Schmoe"
                    />
                  </InputGroup>
                </Form>
              </FormWrapper>
            </Block>
          </>
        ) : (
          <Welcome>
            <h1>Hey, you're account's already set up!</h1>
          </Welcome>
        )}
      </PageWrapper>
    </div>
  );
});

export const PageWrapper = styled.main`
  margin: 0 auto;
  max-width: 600px;
  display: flex;
  flex-direction: column;
  gap: 1rem;
`;

export const LogoBox = styled.div`
  padding: 2rem 0;

  svg {
    width: 25%;
    height: auto;
  }
`;

export const AccountSetup = styled.div`
  padding: 2rem;
  background: var(--color-secondary);
  border-radius: var(--base-border-radius);
  color: var(--color-black);

  p {
    margin-top: 0.75rem;
    font-weight: var(--font-weight-medium);
  }
`;

export const Welcome = styled.div`
  padding: 2rem 5rem 1rem;
`;

export const sectionTitle = css`
  font-size: 0.8em;
  text-transform: uppercase;
  margin-bottom: 0.85rem;
  color: var(--color-white-muted);
`;

export const contentBlock = css`
  padding: 1.5rem;
  border-radius: var(--base-border-radius);
  border: var(--base-border-width) solid var(--color-black-muted);
  transition: border calc(var(--base-transition-out-duration) * 2) 0.5s ease-out;

  &:hover {
    transition: border calc(var(--base-transition-in-duration) * 2) ease-in;
  }

  h2 {
    ${sectionTitle};
  }
`;

export const Block = styled.section`
  ${contentBlock};
`;

export const FormWrapper = styled.div`
  margin-top: 2rem;
  /* ${contentBlock}; */
`;
