import { useUser, withPageAuthRequired } from "@auth0/nextjs-auth0";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import DashboardLayout from "../components/layout/DashboardLayout";
import Form, { InputGroup, InputLabel, Input } from "../components/Form";
import Button, { ButtonIcon } from "../components/Button";
import PlusCircleIcon from "../components/svg/PlusCircle";
import { css } from "@emotion/react";
import styled from "@emotion/styled";
import {
  linkStyles,
  padWithBackgroundStyles,
  padStyles,
} from "../shared/styles";

withPageAuthRequired.getLayout = (page) => (
  <DashboardLayout>{page}</DashboardLayout>
);

export default withPageAuthRequired(function Pages() {
  const { user } = useUser();

  return (
    <div>
      <Head>
        <title>Pages | pblsh</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <PageWrapper>
        <Block>
          <h2>Pages</h2>
          <p>This is still in the works ;)</p>
        </Block>
      </PageWrapper>
    </div>
  );
});

export const PageWrapper = styled.main`
  margin: 0 auto;
  max-width: 600px;
  display: flex;
  flex-direction: column;
  gap: 1rem;
`;

export const Welcome = styled.div`
  padding: 2rem 5rem 1rem;
`;

export const sectionTitle = css`
  font-size: 0.8em;
  text-transform: uppercase;
  margin-bottom: 0.85rem;
  color: var(--color-white-muted);
`;

export const contentBlock = css`
  padding: 1.5rem;
  border-radius: var(--base-border-radius);
  border: var(--base-border-width) solid var(--color-black-muted);
  transition: border calc(var(--base-transition-out-duration) * 2) 0.5s ease-out;

  &:hover {
    transition: border calc(var(--base-transition-in-duration) * 2) ease-in;
  }

  h2 {
    ${sectionTitle};
  }
`;

export const Block = styled.section`
  ${contentBlock};
`;
